### PR TITLE
version 3.5.0 release

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #227 

@asandeep r?

### CODE REVIEW

**Comment by peterbe** [comment]
Released!

**Comment by asandeep** [comment]
> Released!

Awesome! 👍 

Looks like the issue didn't got closed somehow. Shall I go ahead and close manually?

**Comment by peterbe** [comment]
> Looks like the issue didn't got closed somehow. Shall I go ahead and close manually? because I foolishly typed the PULL REQUEST number. Not the issue. I'll close it.

**Comment by dwickwire** [comment]
Thank you for doing this!

**Pull request merged**
