### PR TITLE
start working on a url_fetcher system with requests

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
This is just me pasting code around. It's not going to work yet

**Comment by peterbe** [comment]
Go go go! I'm cheering on from the side.

**Comment by peterbe** [comment]
Hi @graingert!
Any progress on this? You might need to rebase your PR by now.

**Comment by peterbe** [comment]
I'm getting more and more problems with the old `urllib`. 
If you don't have time to work on this, I'd be interested in taken over the branch. Please let me know.

**Comment by graingert** [comment]
Yup go ahead, sorry about leaving this to go stale

**Comment by peterbe** [comment]
I'm taking a much simpler approach. Making `requests` a must.
https://github.com/peterbe/premailer/pull/163

**Pull request closed without merging**
