### PR TITLE
Fix python3.2 syntax error

### PR DESCRIPTION
**Pull request by bogdal**
This PR fixes `SyntaxError` for `python 3.2`.

### CODE REVIEW

**Comment by peterbe** [comment]
Thank you!

**Comment by bogdal** [comment]
It would be nice to see a new release on pypi :+1:

**Comment by peterbe** [comment]
There you go https://pypi.python.org/pypi/premailer/2.8.4

**Comment by bogdal** [comment]
Awesome, thanks @peterbe

**Pull request merged**
