### PR TITLE
Add Python 3.5 to tox and travis and drop Python 3.2 support

### PR DESCRIPTION
**Pull request by pzrq**
Works out of the box for me on OSX El Capitan, let's see what Travis says.

### CODE REVIEW

**Comment by peterbe** [comment]
Would you mind squashing that bug into 1 commit?

**Comment by pzrq** [comment]
Hmm, thoughts on what you'd like to do? 
https://github.com/pypa/pip/commit/b11cb019a47ff0cf3d8a37a0c89d8ae4cf25282f

**Comment by peterbe** [comment]
Then I think we should drop travis support for 3.2 too. That release is getting really old. 

Please add another commit to this PR that drops 3.2 from `tox.ini` and `.travis.yml` and ping me for a merge.

**Comment by pzrq** [comment]
@peterbe Should be good to go with dropping Python 3.2 support.

**Comment by peterbe** [comment]
Ahhh nice!

**Comment by pzrq** [comment]
Thanks @peterbe

**Pull request merged**
