### PR TITLE
3.8.0 release

### PR DESCRIPTION
**Pull request by peterbe**
@CraigRobertWhite r?

### CODE REVIEW

**Comment by CraigRobertWhite** [comment]
Looks good to me. Was a pleasure to contribute.

**Comment by peterbe** [comment]
@CraigRobertWhite You can test https://pypi.org/project/premailer/3.8.0/ now.

**Comment by CraigRobertWhite** [comment]
@peterbe just updated one of my projects to use 3.8.0, it's working.
image

**Comment by peterbe** [comment]
THANK YOU!

**Pull request merged**
