### PR TITLE
Added configurable session

### LINKED ISSUE #256: Add cache support for _load_external_url
It would be handy if one could use `allow_network` to fetch styles and also rely on a cache for speedy results

It might be simple enough to just expose the session creation used for requests.  Then something like [CacheControl](https://2.python-requests.org/en/master/community/recommended/#cachecontrol) could be dropped in as a simple fix or something more advanced like a custom cache wrapper if needed.

### PR DESCRIPTION
**Pull request by thenewguy**
Fixes #256

### CODE REVIEW

**Comment by thenewguy** [comment]
@peterbe Ah can't confirm the test - it says "First-time contributors need a maintainer to approve running workflows".  Please approve

**Comment by thenewguy** [comment]
@peterbe thanks - failure seems to be a configuration error on the runner. any ideas? tox said passed but then job failed

**Comment by peterbe** [comment]
Failing linting?

**Comment by thenewguy** [comment]
> Failing linting?

Whoops yep - didn't realize that lint only ran on py39

**Review by peterbe — APPROVED** [review]
Do you want to convert it from a Draft to Open?

**Comment by peterbe** [comment]
Now you're no longer a first-time contributor! Welcome! And thanks!

**Pull request merged**
