### PR TITLE
Handle CSSUnknownRule

### PR DESCRIPTION
**Pull request by lavr**

### CODE REVIEW

**Comment by peterbe** [comment]
Needs a unit test.

**Comment by peterbe** [comment]
Also, this should probably be mentioned in the README.

**Comment by TZanke** [comment]
added test and opened pull request to your branch which is pull requested here.

https://github.com/lavr/premailer/pull/1

**Comment by peterbe** [comment]
That PR is to merge into `lavr:master`.

All you need to do is make a PR *to* `peterbe:master` that contain https://github.com/peterbe/premailer/pull/202/commits/75f12ad76c0b7dc1ec4ec0010bc9dcb53d92111a and https://github.com/lavr/premailer/pull/1/commits/d6770f3e908a0a754f1aa560d5029b4a9c1d6396

**Comment by peterbe** [comment]
Actually, I took the liberty of putting in @lavr 's change and @TZanke 's test here in this PR: https://github.com/peterbe/premailer/pull/208

**Pull request closed without merging**
