### PR TITLE
add python 3.5 to tox.ini

### PR DESCRIPTION
**Pull request by fuhrysteve**

### CODE REVIEW

**Comment by peterbe** [comment]
Uh? Any idea why Travis can't find that interpreter?

**Comment by peterbe** [comment]
Oh. [This](https://github.com/travis-ci/travis-ci/issues/4794) :(

**Comment by peterbe** [comment]
Interesting that it says "no language set"
http://jmp.sh/hptutFS

**Comment by peterbe** [comment]
bad paste...
screen shot 2016-01-06 at 9 19 24 am

**Comment by fuhrysteve** [comment]
Yeah - sorry about this pull! I'm not sure what the deal is - I have 3.5 working in other projects using travis. I'm not sure why it's not working in this case..

**Comment by peterbe** [comment]
But that doesn't work with tox. The [link I pasted above has a possible fix I believe](https://github.com/travis-ci/travis-ci/issues/4794#issuecomment-143758799). 
Do you want to try that? I suggest you add some yaml comments to explain why you're doing it.

**Comment by fuhrysteve** [comment]
Ok, I will give it a shot later today!

**Comment by peterbe** [comment]
Also, you might need to rebase your branch to get this in https://github.com/peterbe/premailer/pull/154
so that pypy can build lxml.

**Pull request closed without merging**
