### PR TITLE
convert README.md to RST for PyPI

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by peterbe** [comment]
But I like Markdown. It's much friendlier than ReST.
When will PyPI support both?

**Comment by peterbe** [comment]
As you can see in the travis tests, you'll need to [this line](https://github.com/graingert/premailer/blob/fix-readme-on-pypi/setup.py#L16) too.

**Comment by peterbe** [comment]
Would you mind rebasing and incorporating [the change that sneaked in](https://github.com/peterbe/premailer/commit/2034a2fb154fc0dbb87baff44329aa7db17bbbb5)?

**Comment by ionelmc** [comment]
+1

PyPI doesn't support Markdown (there are no plans to support it AFAIK) and RST is quite good anyway.

**Comment by peterbe** [comment]
Once again @graingert impresses me!

**Pull request merged**
