### PR TITLE
When merge style, don't change the style items' order

### PR DESCRIPTION
**Pull request by machinewu**
the same as PR #153
For some wrong operation, make a new PR.

### CODE REVIEW

**Comment by machinewu** [comment]
Flake8 failure, because something wrong about the travis-ci docker while running the test(Job error). It's docker's error(it download python 3.5 failure?! ╮(╯▽╰)╭), rerun test will pass flake8.

**Comment by peterbe** [comment]
Uh? How do we solve this?

**Comment by machinewu** [comment]
Can you rerun that flake8 test instance?

**Comment by peterbe** [comment]
Re-opening means travis is retried.

**Comment by machinewu** [comment]
:+1: got it!

**Pull request merged**
