### PR TITLE
keep classes by default, fixes #33

### LINKED ISSUE #33: keep class attributes
the transform() function replaces the "class" attribute with the appropriate styling, but it also removes the class from the html elements. I need the styling added inline, but the classes to be left within their elements so that my @media (!important) styling can be inserted in after and still have classes to point to within the dom.

Im having a hard time changing your code to meet this needs, do you have any thoughts on how I could keep the classes within the html elements but still inject the inline styling?

### PR DESCRIPTION
**Pull request by peterbe**
Major version bump.

### CODE REVIEW

**Comment by graingert** [comment]
I think it's such a trivial and unlikely to be used piece of code, that I'd rather just remove it and recommend people add their own:
```python
            # now we can delete all 'class' attributes
            for item in page.xpath('//@class'):
                parent = item.getparent()
                del parent.attrib['class']
```

**Comment by peterbe** [comment]
@graingert But I want the library to be as easy as possible. Also, as lazy as possible :)

**Comment by graingert** [comment]
It's your call, but imagine if this feature was not implemented, would it be worth adding?

I don't see a use-case for it.

**Comment by peterbe** [comment]
One usecase is that it's not hard to keep and it's nice to have it there
for people who needed it.

Actually, if you don't have media queries. If you have some really simple
CSS for your HTML emails, then having the `class` attributes still in means
the email gets unnecessarily larger.
I suggest we just keep the functionality around.

On Tue, Jun 7, 2016 at 8:45 AM, Thomas Grainger <notifications@github.com>
wrote:

> It's your call, but imagine if this feature was not implemented, would it
> be worth adding?
>
> I don't see a use-case for it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/peterbe/premailer/pull/167#issuecomment-224269061>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABoc_2Fg2_REhvGVNqOZLI7Z5RBUWkLks5qJWfjgaJpZM4Iv3_H>
> .
>



-- 
Peter Bengtsson
Mozilla Tools & Services

**Pull request merged**
